sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t taariasdckr95/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true taariasdckr95/react-test npm test

after success:
  - docker build -t taariasdckr95/multi-client ./client
  - docker build -t taariasdckr95/multi-nginx ./nginx
  - docker build -t taariasdckr95/multi-server ./server
  - docker build -t taariasdckr95/multi-worker ./worker
    
  #Login into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take images and push into Docker Hub
  - docker push taariasdckr95/multi-client
  - docker push taariasdckr95/multi-nginx
  - docker push taariasdckr95/multi-server
  - docker push taariasdckr95/multi-worker 

deploy:
   provider: elasticbeanstalk
   region: 'us-east-1'
   app: 'multi-docker'
   env: 'MultiDocker-env'
   bucket_name: 'elasticbeanstalk-us-east-1-542767270203'
   bucket_path: 'docker-multi'
   on:
     branch: main
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
  
